// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-UeRfYtb7Ed_2Q3NCgJYg383DoI_8bF4',
    appId: '1:266637425259:web:24ee2d07bedde30c154f2e',
    messagingSenderId: '266637425259',
    projectId: 'byteandbite-73334',
    authDomain: 'byteandbite-73334.firebaseapp.com',
    storageBucket: 'byteandbite-73334.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7aa7MDb5nhCnz-J07b-wf3NWEbWB6wrE',
    appId: '1:266637425259:android:8cd9fdc673f180b8154f2e',
    messagingSenderId: '266637425259',
    projectId: 'byteandbite-73334',
    storageBucket: 'byteandbite-73334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl8gCXRWSE19KRQO50VXFugtK0q_5GkBo',
    appId: '1:266637425259:ios:fc62cff8c2560c69154f2e',
    messagingSenderId: '266637425259',
    projectId: 'byteandbite-73334',
    storageBucket: 'byteandbite-73334.firebasestorage.app',
    iosBundleId: 'com.example.paginaweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl8gCXRWSE19KRQO50VXFugtK0q_5GkBo',
    appId: '1:266637425259:ios:fc62cff8c2560c69154f2e',
    messagingSenderId: '266637425259',
    projectId: 'byteandbite-73334',
    storageBucket: 'byteandbite-73334.firebasestorage.app',
    iosBundleId: 'com.example.paginaweb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-UeRfYtb7Ed_2Q3NCgJYg383DoI_8bF4',
    appId: '1:266637425259:web:7d12f0bcc5b39928154f2e',
    messagingSenderId: '266637425259',
    projectId: 'byteandbite-73334',
    authDomain: 'byteandbite-73334.firebaseapp.com',
    storageBucket: 'byteandbite-73334.firebasestorage.app',
  );
}
